# bot settings
bot_token: 'YOUR_BOT_TOKEN' # support bot token
staffchat_id: 'SUPERGROUP_CHAT_ID' # eg. -123456789
owner_id: 'YOUR_TELEGRAM_ID'
spam_time: 300000 # time (in MS) in which user may send 5 messages
spam_cant_msg: 5

parse_mode: 'Markdown' # Experimental. Do not change unless you know what you are doing. Options: Markdown/MarkdownV2/HTML

allow_private: true # Allow / disallow option for staff to chat privately
direct_reply: true # Set this to true to just forward staff users to a user chat when allow_private
auto_close_tickets: false # Close tickets after answering
anonymous_tickets: true # Include userid in tickets or not
anonymous_replies: true # Include staff member name in response
show_auto_replied: false # Send auto replied msgs to staff chat
show_user_ticket: true # Show ticket id to user
autoreply_confirmation: true # Reply with language.confirmationMessage on each incoming message
clean_replies: false # Remove footer and header from response
pass_start: false # Pass /start command to support directly

signal_enabled: false # Enable/disable signal
signal_number: '+12345689' # Your signal number / account

web_server: false # Enable/disable web server
web_server_port: 8080 # Port for web server

dev_mode: false # Enable/disable dev mode

# customize your language
language:
  startCommandText: 'Here is DataDash Wallet Support Bot, You Can Ask Me Any Thing! Submit a Bug or Ask for Help, We Are Always Here For You! \ æ‚¨å¥½è¿™é‡Œæ˜¯DataDashå®¢æœï¼Œè¯·ç‚¹é€‰ç›¸åº”é—®é¢˜ï¼Œæäº¤é”™è¯¯è¯·æˆªå›¾å’Œæè¿°ã€‚\Hier ist DataDash Wallet Support Bot, Sie kÃ¶nnen mich jede Sache fragen! Reichen Sie einen Fehler ein oder bitten Sie um Hilfe, wir sind immer fÃ¼r Sie da!'
  faqCommandText: 'Check the MXC zkEVM design [here](https://wannsee.mxc.com/docs/intro)'
  helpCommandText: "*Available commands:* /help /faq /id"
  helpCommandStaffText: "*Available commands:*\n
    /start - Get a little introduction \n
    /faq - Show frequently asked questions \n
    /open - *Staff* Shows a list of open tickets \n
    /reopen - *Staff* Reopen a closed ticket \n
    /close - *Staff* Reply to a ticket with this to close and unban \n
    /clear - *Staff* Closes all tickets \n
    /ban - *Staff* Ban a user from the chat \n
    /unban - *Staff* Unban a user"
  confirmationMessage: "Thank you for contacting us. We will answer as soon as possible. \ æ„Ÿè°¢æ‚¨çš„ä¿¡æ¯ï¼Œæˆ‘ä»¬ä¼šå°½å¿«å›å¤ \ Vielen Dank, dass Sie uns kontaktiert haben. Wir werden so schnell wie mÃ¶glich antworten. "
  blockedSpam: 'You sent quite a number of questions in the last while. Please calm down and wait until staff reviews them.'
  ticket: 'Ticket'
  closed: 'closed'
  acceptedBy: 'was accepted by'
  dear: 'Hi'
  regards: 'Regards,'
  from: 'from'
  language: 'Language'
  msg_sent: 'Message sent to user'
  file_sent: 'File sent to user'
  usr_with_ticket: 'User with ticket'
  banned: 'banned'
  replyPrivate: 'Reply in private'
  services: 'Select a service from the list below \ è¯·åœ¨ä¸‹æ–¹ç‚¹é€‰å¯¹åº”é—®é¢˜ \ WÃ¤hlen Sie eine Dienstleistung aus der folgenden Liste '
  customer: 'customer'
  msgForwarding: 'You messages will now be forwarded to vendors of the group: \æ‚¨çš„æ¶ˆæ¯ä¼šè¢«è½¬äº¤ç»™ç›¸åº”éƒ¨é—¨ \ Ihre Nachrichten werden nun an die VerkÃ¤ufer der Gruppe weitergeleitet: '
  back: 'Go back'
  whatSubCategory: 'Which subcategory describes your needs the best? \ ä¸‹é¢å“ªä¸ªç±»åˆ«èƒ½æè¿°æ‚¨çš„é—®é¢˜ï¼Ÿ\ Welche Unterkategorie beschreibt Ihre BedÃ¼rfnisse am besten? '
  prvChatEnded: 'Private chat ended.'
  prvChatOpened: 'Private Chat opened with customer.'
  prvChatEnd: 'End Private chat'
  prvChatOpenedCustomer: 'Opened private chat'
  instructionsSent: 'Instructions were sent to you in private chat.'
  openTickets: 'Open Tickets'
  support: 'Support'
  prvChatOnly: 'This command can be used in private chat only.'
  ticketClosed: 'Your ticket was closed by our staff. You can open a new ticket at any time.'
  links: 'Direct support links'
  textFirst: 'Please send us a message before sending an image so that we can help you better.'
  ticketClosedError: 'You cannot reply to a closed ticket.'
  automatedReply: 'This is an automated reply.'
  automatedReplyAuthor: 'MXCBot.'
  doesntHelp: 'This does not help.'
  automatedReplySent: 'Automated reply was send to the user.'
  ticketReopened: 'Ticket reopened.'
  regardsGroup: 'MXC DAO Support'

autoreply:
  - question: 'not'
    answer: "To report a bug, you can create a ticket here. Just put any screenshot or take a picture would be ok!"
  - question: 'are you sure?'
    answer: 'Yes.'


categories:
  - name: "ğŸš¨Bugs"
    tag: "#other"
    msg: "Please put the screenshot or picture and we will fix the bug!\ è¯·æˆªå›¾æˆ–è€…å½•å±å‘ç»™æˆ‘ä»¬ï¼Œæˆ‘ä»¬ä¼šå°½å¿«ä¿®å¤\ Bitte fÃ¼gen Sie den Screenshot oder das Bild ein und wir werden den Fehler beheben!"
    group_id: "-910551710"
  - name: "M2Pro"
    subgroups:
    - name: "F&Q"
      group_id: "-910551710"
    - name: "Problem"
      group_id: "-910551710"
    - name: "Suggestion"
      group_id: "-910551710"

  - name: "Neo"
    subgroups:
    - name: "F&Q"
      group_id: "-910551710"
    - name: "Problem"
      group_id: "-910551710"
    - name: "Suggestion"
      group_id: "-910551710"
  - name: "ISO"
    group_id: "-910551710"
  - name: "NFT"
    group_id: "-910551710"
  - name: "Contact"
    group_id: "-910551710"
  - name: "ä¸­æ–‡è”ç³»"
    group_id: "-910551710"
  - name: "DACHğŸ‡©ğŸ‡ª"
    group_id: "-910551710"
